### ISSUE TITLE
Support querying data from Phala network

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-graph#48]
This work includes two parts

* [x] substrate-based network data, since phala is part of kusama parachain
* [x] ethereum network data, since phala has its token also on Ethereum.
* [x] binance smart chain data, as phala is also on there

**Comment by geastwood** [comment]
Feel free to leave your opinions here.

**Comment by bdmason** [comment]
Regarding Khala (wss://khala-api.phala.network) Subsquid will be creating an archive (database of events & extrinsics for that network) for us, this means we can just focus on the mappings.

This does mean we are briefly blocked, but we have a lot of research to do on the Khala pallets and can do a lot of the work without running the code.
